In [1]:
import numpy as np

def knight_tour(n):
    board = [[-1 for i in range(n)] for j in range(n)]
    
    # Start the knight's tour from the top-left corner (0, 0)
    if knight_tour_helper(n=n, board=board, x=0, y=0, counter=0):
        print(np.array(board))
    else:
        print("No solution exists")

def knight_tour_helper(n, board, x, y, counter):
    if counter == n * n:  # Base case: all squares are visited
        return True
    
    # Check if the current position is out of bounds or already visited
    if x < 0 or x >= n or y < 0 or y >= n or board[y][x] != -1:
        return False
    
    # Mark the current square as visited
    board[y][x] = counter
    
    # Possible moves a knight can make
    x_moves = [-2, -2, -1, -1, 1, 1, 2, 2]
    y_moves = [-1, 1, -2, 2, -2, 2, -1, 1]
    
    # Try all next moves from the current coordinate
    for x_move, y_move in zip(x_moves, y_moves):
        if knight_tour_helper(n, board, x + x_move, y + y_move, counter + 1):
            return True
    
    # Backtrack: Unmark the current square as visited
    board[y][x] = -1
    return False

knight_tour(8)


[[ 0  9 30 63 32 25 52 61]
 [11  6 27 24 29 62 33 50]
 [ 8  1 10 31 26 51 60 53]
 [ 5 12  7 28 23 34 49 40]
 [ 2 17  4 35 48 39 54 59]
 [13 20 15 22 45 56 41 38]
 [16  3 18 47 36 43 58 55]
 [19 14 21 44 57 46 37 42]]


In [2]:
import numpy as np

# Knight's possible movements in terms of x and y coordinates
knight_moves = [
    (2, 1), (1, 2), (-1, 2), (-2, 1),
    (-2, -1), (-1, -2), (1, -2), (2, -1)
]

def is_valid_move(x, y, n, board):
    """Check if the move is inside the board and not yet visited."""
    return 0 <= x < n and 0 <= y < n and board[y][x] == -1

def get_degree(x, y, n, board):
    """Calculate the degree of the current position (number of possible moves)."""
    degree = 0
    for move in knight_moves:
        new_x, new_y = x + move[0], y + move[1]
        if is_valid_move(new_x, new_y, n, board):
            degree += 1
    return degree

def warnsdorff_tour(n):
    """Solve the Knight's Tour problem using Warnsdorff's algorithm."""
    board = [[-1 for _ in range(n)] for _ in range(n)]
    # Start the knight's tour from the top-left corner (0, 0)
    x, y = 0, 0
    board[y][x] = 0  # Starting point

    for move_count in range(1, n * n):
        min_degree = float('inf')
        next_move = None
        
        # Try all possible knight moves
        for move in knight_moves:
            new_x, new_y = x + move[0], y + move[1]
            if is_valid_move(new_x, new_y, n, board):
                degree = get_degree(new_x, new_y, n, board)
                # Choose the move with the lowest degree (minimum number of onward moves)
                if degree < min_degree:
                    min_degree = degree
                    next_move = (new_x, new_y)

        if next_move is None:
            print("No solution exists!")
            return False
        
        # Move to the chosen next move
        x, y = next_move
        board[y][x] = move_count

    print(np.array(board))
    return True

# Test the function with an 8x8 chessboard
warnsdorff_tour(8)


[[ 0  3 56 19 40  5 42 21]
 [33 18  1  4 57 20 39  6]
 [ 2 55 34 59 36 41 22 43]
 [17 32 47 52 45 58  7 38]
 [48 13 54 35 60 37 44 23]
 [31 16 51 46 53 26 61  8]
 [12 49 14 29 10 63 24 27]
 [15 30 11 50 25 28  9 62]]


True

In [4]:
def count_ways_with_k_coins(matrix, k):
    n = len(matrix)
    m = len(matrix[0])

    # Initialize the DP table with empty lists
    dp = [[[] for _ in range(m)] for _ in range(n)]
    
    # Start from the top-left corner (0, 0) with the initial number of coins
    if matrix[0][0] <= k:
        dp[0][0] = [[(0, 0, matrix[0][0])]]  # Store path with initial coin count
    
    # Fill the DP table
    for i in range(n):
        for j in range(m):
            for path in dp[i][j]:
                current_coins = path[-1][2]  # Number of coins collected so far
                # Move right
                if j + 1 < m and current_coins + matrix[i][j+1] <= k:
                    new_path = path + [(i, j + 1, current_coins + matrix[i][j + 1])]
                    dp[i][j+1].append(new_path)
                
                # Move down
                if i + 1 < n and current_coins + matrix[i+1][j] <= k:
                    new_path = path + [(i + 1, j, current_coins + matrix[i + 1][j])]
                    dp[i+1][j].append(new_path)
    
    # Extract paths that end at bottom-right corner with exactly k coins
    valid_paths = []
    for path in dp[n-1][m-1]:
        if path[-1][2] == k:  # Check if the last cell in the path has exactly k coins
            valid_paths.append(path)

    return valid_paths

# Example input
matrix = [
    [1, 2, 3],
    [4, 6, 5],
    [3, 2, 1]
]
k = 12

# Calculate the number of ways and paths
valid_paths = count_ways_with_k_coins(matrix, k)

# Print all valid paths
print(f"Number of ways to reach bottom right with exactly {k} coins: {len(valid_paths)}")
print("Paths:")
for path in valid_paths:
    path_cells = [(i, j) for (i, j, c) in path]  # Extract cell coordinates from path
    print(path_cells)


Number of ways to reach bottom right with exactly 12 coins: 2
Paths:
[(0, 0), (0, 1), (0, 2), (1, 2), (2, 2)]
[(0, 0), (0, 1), (1, 1), (2, 1), (2, 2)]


In [2]:
def compute_lps_array(pattern):
    length = 0  # Length of the previous longest prefix suffix
    lps = [0] * len(pattern)
    
    i = 1
    while i < len(pattern):
        if pattern[i] == pattern[length]:
            length += 1
            lps[i] = length
            i += 1
        else:
            if length != 0:
                length = lps[length - 1]
            else:
                lps[i] = 0
                i += 1
    return lps

def kmp_search(text, pattern):
    m = len(pattern)
    n = len(text)
    
    lps = compute_lps_array(pattern)
    
    i = 0  # index for text
    j = 0  # index for pattern
    
    while i < n:
        if pattern[j] == text[i]:
            i += 1
            j += 1
            
        if j == m:
            print(f"Pattern found at index {i - j}")
            j = lps[j - 1]
        
        elif i < n and pattern[j] != text[i]:
            if j != 0:
                j = lps[j - 1]
            else:
                i += 1

# Example usage:
text = "AAAAAAAAAAB"
pattern = "AAAB"
kmp_search(text, pattern)


Pattern found at index 7


In [3]:
def LongComSubS(st1, st2):
  ans = 0
  for a in range(len(st1)):
         for b in range(len(st2)):
            k = 1
            while ((a + k) < len(st1) and (b + k) < len(st2)
        and st1[a + k] == st2[b + k]):
                k = k + 1;
            ans = max(ans, k)
  return ans

if __name__ == '__main__':
 
    A = 'longest'
    B = 'stone'
    i = len(A)
    j = len(B)
    print('The longest common substring in a string is', LongComSubS(A, B))

The longest common substring in a string is 3


In [4]:
def LCS(X, Y, m, n):
 
    maxLength = 0          
    endingIndex = m        
    lookup = [[0 for x in range(n + 1)] for y in range(m + 1)]
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            if X[i - 1] == Y[j - 1]:
                lookup[i][j] = lookup[i - 1][j - 1] + 1
                if lookup[i][j] > maxLength:
                    maxLength = lookup[i][j]
                    endingIndex = i
    return X[endingIndex - maxLength: endingIndex]
if __name__ == '__main__':
    X = 'ABC'
    Y = 'BABA'
    m = len(X)
    n = len(Y)
    print('The longest common substring is', LCS(X, Y, m, n))

The longest common substring is AB


In [1]:
def printSubStr(str, low, high):
    for i in range(low, high + 1):
        print(str[i], end = "")
def longestPalSubstr(str):
    n = len(str)
    maxLength = 1
    start = 0
    for i in range(n):
        for j in range(i, n):
            flag = 1
            for k in range(0, ((j - i) // 2) + 1):
                if (str[i + k] != str[j - k]):
                    flag = 0
            if (flag != 0 and (j - i + 1) > maxLength):
                start = i
                maxLength = j - i + 1
    print("Longest palindrome subString is: ", end = "")
    printSubStr(str, start, start + maxLength - 1)
    return maxLength

if __name__ == '__main__':
    str = input()
    print("\nLength is: ", longestPalSubstr(str))


 AAAAABBAA


Longest palindrome subString is: AABBAA
Length is:  6


In [2]:
def longestPalSubstr(string):
    n = len(string) # calculating size of string
    if (n < 2):
        return n 
    start=0
    maxLength = 1
    for i in range(n):
        low = i - 1
        high = i + 1
        while (high < n and string[high] == string[i] ):                              
            high=high+1
       
        while (low >= 0 and string[low] == string[i] ):                
            low=low-1
        while (low >= 0 and high < n and string[low] == string[high] ):
          low=low-1
          high=high+1
        length = high - low - 1
        if (maxLength < length):
            maxLength = length
            start=low+1
    print ("Longest palindrome substring is:",end=" ")
    print (string[start:start + maxLength])
    return maxLength
if __name__ == '__main__':
    str = input()
    print("\nLength is: ", longestPalSubstr(str))

 AABA


Longest palindrome substring is: ABA

Length is:  3


In [1]:
def LD(s, t):
    # If the first string is empty, the distance is the length of the second string
    if s == "":
        return len(t)
    
    # If the second string is empty, the distance is the length of the first string
    if t == "":
        return len(s)
    
    # If the last characters of the two strings are the same, no substitution is needed (cost = 0)
    if s[-1] == t[-1]:
        cost = 0
    else:
        # If the last characters are different, substitution is required (cost = 1)
        cost = 1
    # Calculate the minimum cost of:
    # 1. Removing the last character from the first string (s[:-1], t) + 1
    # 2. Removing the last character from the second string (s, t[:-1]) + 1
    # 3. Substituting the last characters of both strings (s[:-1], t[:-1]) + cost
    res = min([LD(s[:-1], t) + 1,
               LD(s, t[:-1]) + 1, 
               LD(s[:-1], t[:-1]) + cost])
    
    # Return the result of the minimum edit distance
    return res

print(LD("Python", "Peithen"))

    



3


In [6]:
#Minimum cost path
R = 3
C = 3
def minCost(cost, m, n):
 
    tc = [[0 for x in range(C)] for x in range(R)]
    tc[0][0] = cost[0][0]
    for i in range(1, m+1):
        tc[i][0] = tc[i-1][0] + cost[i][0]
    for j in range(1, n+1):
        tc[0][j] = tc[0][j-1] + cost[0][j]
    for i in range(1, m+1):
        for j in range(1, n+1):
            tc[i][j] = min(tc[i-1][j-1], tc[i-1][j], tc[i][j-1]) + cost[i][j]
    return tc[m][n]
 
# Driver program to test above functions
cost = [[1, 2, 3],
        [4, 8, 2],
        [1, 5, 3]]
print(minCost(cost, 2, 2))



8


In [1]:
def count(S, n, target):
    if target == 0:
        return 1
    if target < 0 or n < 0:
        return 0
    incl = count(S, n, target - S[n])
    excl = count(S, n - 1, target)
    return incl + excl
if __name__ == '__main__':
    S = [1, 2, 3]
    target = 4
    print('The total number of ways to get the desired change is',
        count(S, len(S) - 1, target))


The total number of ways to get the desired change is 4


In [2]:
def getNumberOfWays(N, Coins):
    ways = [0] * (N + 1);
    ways[0] = 1;
    for i in range(len(Coins)):
        for j in range(len(ways)):
            if (Coins[i] <= j):
                ways[j] += ways[(int)(j - Coins[i])];
    return ways[N];
 
def printArray(coins):
    for i in coins:
        print(i);

if __name__ == '__main__':
    Coins = [1, 5, 10];
    print("The Coins Array:");
    printArray(Coins);
    print("Solution:",end="");
    print(getNumberOfWays(12, Coins));


The Coins Array:
1
5
10
Solution:4


In [1]:
def maxSubArraySum(arr,size):
    
    max_till_now = arr[0]
    max_ending = 0
    
    for i in range(0, size):
        max_ending = max_ending + arr[i]
        if max_ending < 0:
            max_ending = 0
        
        
        elif (max_till_now < max_ending):
            max_till_now = max_ending
            
    return max_till_now

arr = [-2, -3, 4, -1, -2, 5, -3]
print("Maximum Sub Array Sum Is" , maxSubArraySum(arr,len(arr)))

Maximum Sub Array Sum Is 6


In [4]:
def partition(l, r, nums):
    # Last element will be the pivot and the first element the pointer
    pivot, ptr = nums[r], l
    for i in range(l, r):
        if nums[i] <= pivot:
            # Swapping values smaller than the pivot to the front
            nums[i], nums[ptr] = nums[ptr], nums[i]
            ptr += 1
    # Finally swapping the last element with the pointer indexed number
    nums[ptr], nums[r] = nums[r], nums[ptr]
    return ptr

def quicksort(l, r, nums):
    if len(nums) == 1:  # Terminating Condition for recursion. VERY IMPORTANT!
        return nums
    if l < r:
        pi = partition(l, r, nums)
        quicksort(l, pi-1, nums)  # Recursively sorting the left values
        quicksort(pi+1, r, nums)  # Recursively sorting the right values
    return nums
arr=[]
n=int(input())
for i in range(n):
    arr.append(int(input()))
print(arr)
quicksort(0,n-1,arr)
print(arr)

 5
 1
 4
 6
 8
 9


[1, 4, 6, 8, 9]
[1, 4, 6, 8, 9]


In [5]:
def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quick_sort(left) + middle + quick_sort(right)

def sort_second_half(arr):
    n = len(arr)
    if n <= 1:
        return arr
    # Find the midpoint
    mid = n // 2
    # Sort the second half using quicksort
    sorted_second_half = quick_sort(arr[mid:])
    # Combine first half with sorted second half
    return arr[:mid] + sorted_second_half

# Sample inputs
arr1 = [2, 1, 3, 5, 7, 8, 9]
arr2 = [2, 6, 7, 14, 8, 9, 30]

# Sorting the second half of the array
print(sort_second_half(arr1))  # Output: [2, 1, 3, 5, 7, 8, 9]
print(sort_second_half(arr2))  # Output: [2, 6, 7, 14, 8, 9, 30]


[2, 1, 3, 5, 7, 8, 9]
[2, 6, 7, 8, 9, 14, 30]


In [2]:
def minJumps(arr, l, h):
    if (h == l):
        return 0
    if (arr[l] == 0):
        return float('inf')
    min = float('inf')
    for i in range(l + 1, h + 1):
        if (i < l + arr[l] + 1):
            jumps = minJumps(arr, i, h)
            if (jumps != float('inf') and
                       jumps + 1 < min):
                min = jumps + 1
 
    return min
arr = [1, 3, 6, 3, 2, 3, 6, 8, 9, ]
arr1=[2,3,1,1,4]
n = len(arr)
n1=len(arr1)
print('Minimum number of jumps to reach','end is', minJumps(arr, 0, n-1))
print('Minimum number of jumps to reach','end is', minJumps(arr1, 0, n1-1))

Minimum number of jumps to reach end is 3
Minimum number of jumps to reach end is 2


In [3]:
def minJumps(arr, n):
    jumps = [0 for i in range(n)]
 
    if (n == 0) or (arr[0] == 0):
        return float('inf')
 
    jumps[0] = 0
    for i in range(1, n):
        jumps[i] = float('inf')
        for j in range(i):
            if (i <= j + arr[j]) and (jumps[j] != float('inf')):
                jumps[i] = min(jumps[i], jumps[j] + 1)
                break
    return jumps[n-1]
arr = [1, 3, 6, 1, 0, 9]
size = len(arr)
print('Minimum number of jumps to reach', 'end is', minJumps(arr, size))


Minimum number of jumps to reach end is 3
